/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_packtpub_store_Store */

#ifndef _Included_com_packtpub_store_Store
#define _Included_com_packtpub_store_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_brovkoroman_store_Store
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_brovkoroman_store_Store_getCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
